### ISSUE TITLE
Creating a TS group for W4M

### ISSUE THREAD

**Issue by bgruening** [workflow4metabolomics/nmr_alignment#3]
Would it be good to create one group for all tools for W4M? For me it is hard to distinguish well maintained and less maintained metabolic tools - and I think with a W4M group this could be easier.

**Comment by lecorguille** [comment]
Can you post this issue on our meta-repo https://github.com/workflow4metabolomics/workflow4metabolomics ?
Thanks

**Comment by mtremblayfr** [comment]
Done.


Marie Tremblay-Franco
New email : marie.tremblay-franco@inra.fr<mailto:marie.tremblay-franco@inra.fr>


[cid:image001.png@01D238FD.68CB9720]

INRA, TOXALIM (Research Centre in Food Toxicology)
Platform MetaboHUB-MetaToul-AXIOM
180 Chemin de Tournefeuille
F-31027 TOULOUSE
France
+33 5 82 06 63 90

www.metatoul.fr <http://www.metatoul.fr/>
www.toulouse.inra.fr/axiomm <http://www6.toulouse.inra.fr/axiomm>
www.toulouse.inra.fr/toxalim<http://www.toulouse.inra.fr/toxalim>

De : Gildas Le Corguillé [mailto:notifications@github.com]
Envoyé : vendredi 25 novembre 2016 10:17
À : workflow4metabolomics/nmr_alignment <nmr_alignment@noreply.github.com>
Objet : Re: [workflow4metabolomics/nmr_alignment] Creating a TS group for W4M (#3)


Can you post this issue on our meta-repo https://github.com/workflow4metabolomics/workflow4metabolomics ?
Thanks

**Comment by bgruening** [comment]
Upps :) Thanks @mtremblayfr!

**Comment by lecorguille** [comment]
@mtremblayfr I didn't target you.  But thanks 😄
